using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace Problem002
{
    /// <summary>
    /// Each new term in the Fibonacci sequence is generated by adding the 
    /// previous two terms. By starting with 1 and 2, the first 10 terms will 
    /// be:
    ///
    ///     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    /// 
    /// By considering the terms in the Fibonacci sequence whose values do not 
    /// exceed four million, find the sum of the even-valued terms.
    /// </summary>
    static class Program
    {
        static void Main()
        {
            var stopwatch = new Stopwatch();

            stopwatch.Start();
            var result = SolveProblem();
            stopwatch.Stop();
            
            Console.WriteLine(string.Format("The result is {0}.", result));
            Console.WriteLine(string.Format("The calculation took {0} ms.", stopwatch.ElapsedMilliseconds));
            Console.WriteLine(string.Empty);
            Console.WriteLine("Press any key to exit.");
            Console.ReadKey(true);
        }

        internal static int SolveProblem()
        {
            var items = new List<int> {1, 2};
            while(true)
            {
                var item = items[items.Count - 2] + items[items.Count - 1];
                if (item > 4000000)
                    break;
                items.Add(item);
            }
            return items.Where(x => x%2 == 0).Sum();
        }
    }

    [TestClass]
    public class TestProblem001
    {
        [TestMethod]
        public void TestSolveProblem()
        {
            Assert.AreEqual(4613732, Program.SolveProblem());
        }
    }
}
